#!/bin/bash
PATH=/apps/anaconda/2.4/bin:$PATH
ifail=0
export PYTHONPATH=../src/:$PYTHONPATH
for demo in script.testgd ; do
    #sed -e "s/HAVE_PYLAB = True/HAVE_PYLAB = False/" < $demo > tmpdemo.py
    #echo "import matplotlib" > tmpdemo.py
    #echo 'matplotlib.use("Agg")' >> tmpdemo.py
    echo running $demo
    NOX11=yes python ../src/runCarouselFit.py < $demo
    if [ $? = 0 ]; then
       echo OK
    else
       echo Failed
       ifail=1
    fi
done
echo exit with ifail=$ifail
exit $ifail
